name: widgets_pack
description: Widgets collection for flutter applications
version: 0.4.0+11

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  chewie: ^1.8.5
  equatable: ^2.0.5
#  extensions_pack: { path: ../extensions-pack }
  extensions_pack: ^2.3.0+2
  flutter: { sdk: flutter }
  flutter_spinkit: ^5.2.1
  intl: ^0.19.0
  linked_scroll_controller: ^0.2.0
  rxdart: ^0.28.0
  skeletonizer: ^1.4.2
  sticky_headers: ^0.3.0+2
  two_dimensional_scrollables: ^0.3.2
  video_player: ^2.9.1
  visibility_detector: ^0.4.0+2
  youtube_player_flutter: ^9.1.1
  youtube_player_iframe: ^5.2.0

dev_dependencies:
  my_linter: ^0.1.0+3

flutter:
  uses-material-design: true
